services:
  - type: web
    name: sltb-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: 3306
      - key: CORS_ORIGIN
        value: https://YOUR_VERCEL_DOMAIN
      - key: JWT_SECRET
        generateValue: true


